### ISSUE TITLE
Doesn't work at all

### ISSUE THREAD

**Issue by larvanitis** [MaartenDesnouck/google-apps-script#35]
```
> npm i -g google-apps-script
# successful without errors or warnings

> gas auto
module.js:472
    throw err;
    ^

Error: Cannot find module './functions/getmetadata.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/leon/.npm-global/lib/node_modules/google-apps-script/lib/remote-delete.js:2:19)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)

# error thrown for any "gas" command I tried

> node -v
v7.10.0

> npm -v
4.6.1
```

**Comment by MaartenDesnouck** [comment]
Ow, that's not good. Thanks for notifying me.
Just published a new version that should fix it.

**Comment by larvanitis** [comment]
Yes it worked. Just a small glitch after `gas auth` it got stuck on `You are succesfully authenticated` and I had to kill it. Runs well after that (no need to re-auth).

Thanks.

**Comment by MaartenDesnouck** [comment]
Ok, cool. 
Don't hesitate to create a new issue if something comes up or if you have a question.
